

# Getting started {#getting-started}

**There are two places to write R code**:

1. <u>The R console</u>. This is where code is run. If you write directly into the console, each time you hit `enter` it will run what you wrote. If you open R without RStudio, R will just show the console. Try it.
2. <u>Scripts</u>. An R script is basically a text file (but, if using RStudio, with a .R extension). This is where code is saved. You send whole scripts or bits of them to the console for execution. 

<b>Use RStudio</b>, which makes writing, running and saving scripts easy. Although R is open source, RStudio is commercial software, but the standard version is free of charge, and if it doesn't stay that way someone will hopefully develop an open-source alternative. Some small parts of this document are specific to using R in RStudio. 

**To get started with RStudio**:

1. Download and install R and RStudio (for windows, from here https://cran.rstudio.com/ and here https://www.rstudio.com/products/rstudio/download/#download), and open RStudio.
2. Click "File", then "New file", then "R Script".
3. Write code into the script.
4. Run code by highlighting it and typing `ctrl+enter`, or run a line by hitting `ctrl+enter` when your cursor is on that line, or run the whole script down to your cursor by typing `ctrl+alt+b`.
5. Save the script if you want to keep it.

**TIP: save your R scripts, not your R 'sessions'** (i.e. the collection of data objects your script has created). Rather than opening a saved session, it's better to recreate it by running your saved script. Then you have the R objects you need <u>and</u> a record of how they were created <u>and</u> the ability to reproduce them.

**TIP: regularly run your whole script, to check everything still works.** Before each re-run, clear your session to make sure it's starting fresh. You can clear your session by typing `ctr + shift + F10`, but RStudio first needs to have some settings adjusted. This is common practice and needs to be done due to [legacy issues](https://community.rstudio.com/t/defaults-of-saving-and-restoring-workspace/939). 

1. Click "Tools, then "Global Options".
2. In "R General" and "Basic", under "Workspace", make sure "Restore .RData into workspace at startup" is unticked, and "Save workspace to .RData on exit:" is set to "Never".
3. Click "Apply". 


**Other commonly used RStudio functionality**:

* <u>RStudio projects</u> are useful for grouping files that belong to the same piece of work, such as scripts that relate to each other, input files read by the script/s (e.g. datasets stored locally), and outputs. These are discussed in section \@ref(import-data-projects)
* <u>R Markdown</u> is great for presenting code/output/text to someone that will be more interested in reading the content than running the code themselves. For example, this document was produced in R Markdown. But <u>only use it for these purposes</u> -- it wasn't intended to be used for general coding, which standard scripts are better for.

## What is a line of R code? {#getting-started-what-is}

These are things worth knowing before you start:

* **Comments**: R ignores any line that starts with `#`, regardless of what is after it. If `#` appears partway through a line, everything after the `#` is ignored.
* **R is case sensitive**. 
* **R uses sequential execution**. R runs code one line at a time. The results of one line are produced, and ready to use, before the next line is run. Lines are separated by typing `enter`.
   * <u>Splitting lines</u>: R reads multiple lines as one if the first line(s) have an unfinished operation, such as `(` without `)`, or `+` with nothing afterward until the next line.
   * <u>Pipes</u>: The ‘pipe’ operator `%>%`, from the magrittr package, slightly modifies the concept of ‘a line of R code’. This is discussed in section \@ref(data-table-and-magrittr).   
*	**Assignment** (`<-`): Most lines of R code are an assignment, to create or modify a data object. 
    * Assignment can create a new object. For example, `y <- 3` creates a new object called `y`, containing `3`.
    * The assignment operator `<-` gives the RHS data object (e.g. `3`) the name (AKA symbol) on the LHS (e.g. `y`), and stores it in your session’s ‘environment’. If an object of that name already existed, it is over-written. 
        * Have the 'Environment' pane in RStudio open when you run an assignment, and you will see the object appear when it is assigned.
    * Assignment can also modify an existing object. To do this, instead or having just an object name to the left of `<-`, 'index' an existing object to refer to a specific component of it. Indexing is discussed more shortly.
    * The operation on the right of `<-` is done before the name is assigned. So, for example, `x <- x + 1` does not cause a contradiction; it uses the pre-existing `x` on the right then creates the new `x` on the left.
* **Object names**: names can be any text without spaces, but cannot start with numbers. Most people use underscores instead of spaces. Some old dogs use a dot.
*	**Operations**: an operation can be run without an assignment, which will usually just display the result of that operation in the console.

## Coding style

Make your code easily readable, for your later self and for others. Some tips:

* <u>Keep each line of your script within 90 characters</u>. Nobody likes having to scroll left and right to look at code. Achieve this by splitting your lines as mentioned in section \@ref(getting-started-what-is). Some use 80 characters.
* <u>Liberally comment your code</u>. It's also usually better to describe what you're doing, rather than how you're doing it. When the reader knows the 'what', they can usually get the 'how' from the code.
* <u>Follow a style guide</u>, such as Hadley Wickham's (http://adv-r.had.co.nz/Style.html) or whatever you find and like. The important thing is that your code is readable, which this will help with.
* <u>Spend time cleaning your code</u>, after you've first got it working, if the code is worth keeping. Code is clean when it achieves its purpose in close to as few steps as possible, and is neatly laid and out and commented. If your code isn't clean, it's reasonably likely to have mistakes that haven't been noticed. 

## Base R and installing packages {#getting-started-packages}

<b>Base R</b> refers to R without any additional packages installed, which is what you get when you first install R. This document focuses mostly on base R, which can do a vast range of things. Packages build on base R to add functionality, but rarely do anything related to data manipulation that cannot be done in base R. Rather, they're usually intended to make doing that thing easier, by reducing the amount of code required or making the operations faster. 

<b>To use a package</b>:

1. <u>Install</u> it on your computer by running `install.packages('<package name>')` in the console, for example `install.packages('data.table')`. This only needs to be done once.
2. <u>Load</u> it each time you open a new R session, by running `library(<package name>)`, for example `library(data.table)`. Write it into the top of the script, for visibility. This brings its functions into your 'namespace' environment and makes them available to call.
    * Alternatively, you can call a function from a package that is installed but not loaded, by typing the package name with `::`. For example, `data.table::melt()` calls the `melt()` function without data.table needing to be loaded. This avoids bringing the package's functions into the namespace environment and can help prevent function-name duplication.

**Careful**: Using additional packages does some bring costs, like package dependencies, potential function-name duplication, and small overheads. Don't let that stop you. Just do this: only start relying on an additional package if it provides a noticeable benefit over what you have already. Also, if your code is running critical processes, make sure you're managing these risks.

A few widely used packages can change how the R syntax looks, so if after reading sections \@ref(getting-started) and \@ref(object-types), you see R code that still looks foreign to you, this is probably the reason. Section \@ref(data-table-and-magrittr) covers that.

## Example code to play with


```{r eval=FALSE}
### Generate some mock variables and run a simple regression on them.
# Set your desired sample size
samp_size <- 1000
# Set the regression parameters
alpha <- 0.75
beta <- 2
# Create an x variable vector, as a sequence from 1 to the sample size
x <- seq(1, samp_size)
# Do the same thing another way (the operator ':' creates a sequence of integers)
x2 <- 1:samp_size
# Show that they're the same (an example of operation without assignment).
identical(x, x2)
# Remove the unneeded one.
rm(x2)
# Generate the regression residuals by randomly selecting from a normal distribution
e <- rnorm(n=samp_size)
# Show the chosen parameters
alpha
beta
# Show the x variables and residuals. Just look at the first few values.
head(x)  # alternatively the tail() function shows the last few values. 
head(e)
# Generate the left-hand-side y variable from the components already specified.
# The assignment is unnecessarily split over two lines, for illustration.
y <- alpha + 
  (beta * x) + e
# Regress the y variable on the x variable. lm() is the standard function for regression.
reg_output <- lm(y ~ x)
# Report the output from regression
reg_output
summary(reg_output)

### Exercise for the interested:
# - Rerun the code a bunch of times, changing the sample size (e.g. 10, 100, 10 000, etc).
#   (Even with the same sample size the results will change, because rnorm gives different
#   values each time.)
# - See if you notice a pattern between the sample size, and how close your specified 
#   alpha and beta parameters are to the regression coefficients. 
# - This pattern is a 'law of large numbers' at work.
```

